name: DFPlugin
version: 1.0
author: Wonk0
website: https://dfspigot.wonk2.repl.co/
main: me.wonk2.DFPlugin
api-version: 1.19
depend:
  - WorldEdit
commands:
  dfspigot:
    description: QOL Commands for DF Spigotifier
    usage: /dfspigot [load | set | end] [build | origin | threads]